[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/discover"
  to = "/discover/index.html"
  status = 200

[[redirects]]
  from = "/wallet"
  to = "/wallet/index.html"
  status = 200 